# Generated by Django 4.0 on 2022-01-13 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatusChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_obj', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В процессе'), ('done', 'Сделано')], default='new', max_length=11, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='TypeChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_obj', models.CharField(choices=[('task', 'Задача'), ('bug', 'Баг'), ('enhancement', 'Улучшение')], default='task', max_length=12, verbose_name='Тип')),
            ],
        ),
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aim', models.CharField(max_length=200, verbose_name='Задача')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Подробное описание')),
                ('create_date', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата редактировнаия')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status', to='todolist.statuschoice', verbose_name='Статус')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='type', to='todolist.typechoice', verbose_name='Тип')),
            ],
        ),
    ]
