# Generated by Django 4.0 on 2022-01-13 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={'verbose_name': 'Список дел', 'verbose_name_plural': 'Списки дел'},
        ),
        migrations.AlterField(
            model_name='todolist',
            name='status',
            field=models.ForeignKey(default='new', on_delete=django.db.models.deletion.PROTECT, related_name='status', to='todolist.statuschoice', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='type',
            field=models.ForeignKey(default='task', on_delete=django.db.models.deletion.PROTECT, related_name='type', to='todolist.typechoice', verbose_name='Тип'),
        ),
        migrations.AlterModelTable(
            name='todolist',
            table='ToDoList',
        ),
    ]
