# Generated by Django 4.0.1 on 2022-01-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_remove_todolist_type_todolist_type_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='type',
            field=models.ManyToManyField(related_name='aims', to='todolist.TypeChoice'),
        ),
    ]
