# Generated by Django 4.0.1 on 2022-01-17 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_auto_20220117_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='type_old',
        ),
        migrations.DeleteModel(
            name='AimType',
        ),
    ]
