# Generated by Django 4.0.1 on 2022-01-20 10:04

from django.db import migrations, models
import todolist.validators


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0007_remove_todolist_type_old_delete_aimtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='aim',
            field=models.CharField(max_length=200, validators=[todolist.validators.MaxLengthValidator(200), todolist.validators.MinLengthValidator(5)], verbose_name='Задача'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True, validators=[todolist.validators.MaxLengthValidator(2000), todolist.validators.MinLengthValidator(5)], verbose_name='Подробное описание'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='type',
            field=models.ManyToManyField(related_name='aims', to='todolist.TypeChoice', verbose_name='Тип'),
        ),
    ]
