# Generated by Django 4.0.1 on 2022-01-31 05:41

from django.db import migrations, models
import todolist.validators


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0008_alter_todolist_aim_alter_todolist_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(null=True, verbose_name='Дата окончания')),
                ('title', models.CharField(max_length=200, validators=[todolist.validators.MaxLengthValidator(200), todolist.validators.MinLengthValidator(5)], verbose_name='Название проекта')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, validators=[todolist.validators.MaxLengthValidator(200), todolist.validators.MinLengthValidator(5)], verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'db_table': 'Projects',
            },
        ),
    ]
