# Generated by Django 4.0 on 2022-02-22 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0012_alter_todolist_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'permissions': [('can_add_users_to_project', 'Может добавлять пользователей в проект')], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
    ]
